version: "3.7"
services:
  web:
    image: pt/frontend:default
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/app"
    stdin_open: true
    tty: true
