apiVersion: apps/v1
kind: Deployment
metadata:
  name: pt-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-name
  template:
    metadata:
      labels:
        app: my-app-name
        environment: dev
    spec:
      containers:
      - name: pt
        image: gcr.io/turnkey-science-250806/pt:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      imagePullSecrets:
      - name: gcr-json-key