version: '3.7'
services:
  server:
    container_name: periodic-table-server
    image: node:12.8-alpine
    user: 1000:1000
    working_dir: /opt/app
    command: npm run dev
    # expose:
    #   - 3000
    ports:
      - target: 3000
        published: 3000
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./backend
        target: /opt/app
    privileged: false
    stdin_open: true
    tty: true
  client:
    container_name: periodic-table-client
    image: node:12.8-alpine
    user: 1000:1000
    working_dir: /opt/app
    command: npm run dev
    ports:
      - target: 8080
        published: 8080
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/app
    links:
      - server
    privileged: false
    stdin_open: true
    tty: true
