version: "3.7"
services:
  server:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - "./backend:/app"
    stdin_open: true
    tty: true
  client:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - "./frontend:/app"
    links:
      - server
    stdin_open: true
    tty: true
