version: "3.7"
services:
  server:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=development
    volumes:
      - "./backend:/app"
    stdin_open: true
    tty: true
  client:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=development
    volumes:
      - "./frontend:/app"
    links:
      - server
    stdin_open: true
    tty: true
