version: '3.7'
services:
  server:
    container_name: periodic-table-server
    image: node:12.8-alpine
    user: ${UID}:$GID
    working_dir: ${PWD}/backend
    command: yarn dev
    # expose:
    #   - 3000
    ports:
      - target: 3000
        published: 3000
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./backend
        target: ${PWD}/backend
    privileged: false
    stdin_open: true
    tty: true
  client:
    container_name: periodic-table-client
    image: node:12.8-alpine
    user: ${UID}:$GID
    working_dir: ${PWD}/frontend
    command: yarn dev
    ports:
      - target: 8080
        published: 8080
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./frontend
        target: ${PWD}/frontend
    links:
      - server
    privileged: false
    stdin_open: true
    tty: true
